collections:
  - name: "gallery"
    label: "Gallery Page"
    file: "content/gallery.json"   # <--- Remove 'public/'
    fields:
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - { label: "Image", name: "src", widget: "image" }
          - { label: "Alt Text", name: "alt", widget: "string" }
          - { label: "Caption", name: "caption", widget: "string" }
